language: go

go:
  - 1.12.x
  - tip

env:
  - GO111MODULE=on GOPROXY=https://proxy.golang.org

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
